imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @SumoCodersFrameworkErrorBundle/Resources/config/config.yml }
    - { resource: @SumoCodersFrameworkCoreBundle/Resources/config/config.yml }

framework:
  templating:
    assets_version: 1
